### ISSUE TITLE
unknown error: cannot create temp dir for user data dir

### ISSUE THREAD

**Issue by ObaydaAlesawi** [katsana/dusk-crawler#3]
- Library Version: 0.1.6
- Laravel Version: 8.0
- PHP Version: 7.4.12

### Description:
I just copied the example and paste it into my controller, but it gave me an error for no reason!

**Comment by crynobone** [comment]
This isn't a helpful bug report.

**Comment by ObaydaAlesawi** [comment]
@crynobone 
and how could it be helpful?
I just got that bug without any extra details.
